yolo: 
  weights: "pretrained_yolo/best_0.pt" # UPDATE 
  data_dir: "data/data.yaml"           # UPDATE
  verbose: true
  image_size: 160
  save: false

model: 
  refinement: "simple" # "simple" or "basic"
  verbose: false 
  layers: 
    - [128, 64, 2] # C3Ghost 
    - [64, 64]     # DoubleResDSConv
    - [64, 32, 1]  # C3Ghost
    - [32, 16]     # ResDWConv
    - [16, 8]      # ResDWConv
    - [8, 1]       # Output Conv
  num_classes: 1

dataloader: 

  # Dataset Parameters
  root_path:  "data/stacked_segmentation_0" # UPDATE "3_fold_dataset/stacked_segmentation_0"
  image_dir: "images"
  mask_dir: "labels"
  image_size: 160
  use_augmentation: true
  subsample: 1.0
  
  # DataLoader Parameters
  batch_size: 16 # UPDATE 128
  num_workers: 10
  use_shuffle: false
  use_persistent_workers: false
  use_pin_memory: false

trainer: 
  training:    
    # General                           
    epochs: 1 # UPDATE 75
    use_mix_precision: true

    is_load_and_train: false
    load_and_train_path: null

    gradient_clip: 1.0 
    verbose: true         

  early_stopping: 
    enabled: true
    patience: 10
    delta: 0.001 # 1e-3
    metric: "dice"
    mode: "max" 
    start_epoch: 50
    
  optimizer:                          
    name: adamW           # see registry
    learning_rate: 0.0001 # 1e-4            
    weight_decay: 0.0                     
    
  scheduler:           # optional block
    name: cosine        # see registry
    kwargs:             # passed as-is
      T_max: 10
  
  device: "cuda"